language: python
python:
  - "3.3"
# command to install dependencies
install:
  - pip install paramiko==2.1.2
  - pip install nose pylint
# command to run tests
script: find . -name "*.py" | xargs pylint -E
